services:
  shelter:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
      - /app/.husky
      - /app/.next
      - /app/.vscode
      - /app/node_modules
      - /app/out
    ports:
      - 3000:3000
    command: [sh, -c, "npm ci && npm run build && npm run serve"]
