[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[redirects]]
  from = "/api"
  to = "https://book.naturstyrelsen.dk/includes/branding_files/naturstyrelsen/includes/inc_ajaxbookingplaces.asp"
  status = 200